

export const CATEGORIES = [
  { id: 'words', name: 'Wörter', icon: 'BookOpen' },
  { id: 'laws', name: 'Kuriose Gesetze', icon: 'Gavel' },
  { id: 'facts', name: 'Fun Facts', icon: 'Sparkles' },
  { id: 'traditions', name: 'Kuriose Bräuche', icon: 'Globe' },
  { id: 'slogans', name: 'Werbeslogans', icon: 'Megaphone' },
  { id: 'jobs', name: 'Kuriose Berufe', icon: 'Briefcase' }
];

export const HP_QUESTIONS = [
    { 
        q: "Was bewirkt der Zauberspruch 'Orchideous'?", 
        a: "Er lässt Blumen aus der Zauberstabspitze sprießen",
        book: "Harry Potter und der Feuerkelch",
        info: "Mr. Ollivander nutzt diesen Spruch bei der Eichung der Zauberstäbe vor dem Trimagischen Turnier, um Fleur Delacours Stab zu testen."
    },
    { 
        q: "Was ist ein 'Glumbumble'?", 
        a: "Ein graues, flauschiges Fluginsekt, das Melancholie verursacht",
        book: "Phantastische Tierwesen und wo sie zu finden sind",
        info: "Der Honig (Melasse) dieser Insekten ruft Schwermut hervor und wird als Gegenmittel gegen die Hysterie nach dem Verzehr von Alihotsy-Blättern genutzt."
    },
    { 
        q: "Wozu dient ein 'Geheimnis-Sensor'?", 
        a: "Er vibriert, wenn Lügen oder Verheimlichungen in der Nähe sind",
        book: "Harry Potter und der Feuerkelch",
        info: "Filch benutzt ihn oft, um Schüler zu kontrollieren. Im 4. Band steht einer in Moody's Büro, der aber wegen der vielen Lügen der Schüler ständig summt."
    },
    { 
        q: "Was passiert beim Zauberspruch 'Waddiwasi'?", 
        a: "Er schleudert kleine Objekte (z.B. Kaugummi) gezielt weg",
        book: "Harry Potter und der Gefangene von Askaban",
        info: "Remus Lupin wendet diesen Spruch an, um einen Kaugummi, den Peeves ins Schlüsselloch gesteckt hat, diesem direkt in die Nase zu schießen."
    },
    { 
        q: "Was ist die besondere Eigenschaft von 'Bubotubler-Eiter'?", 
        a: "Er ist ein hervorragendes Mittel gegen hartnäckige Akne",
        book: "Harry Potter und der Feuerkelch",
        info: "Im Kräuterkunde-Unterricht müssen die Schüler den Eiter aus den Pflanzen quetschen. Später nutzt Hermine ihn (verdünnt), um sich für den Ball hübsch zu machen."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Densaugeo'?", 
        a: "Er lässt die Zähne des Opfers extrem schnell wachsen",
        book: "Harry Potter und der Feuerkelch",
        info: "Draco Malfoy trifft Hermine damit ungewollt bei einem Duell auf dem Gang. Ihre Vorderzähne wachsen daraufhin bis zum Kragen."
    },
    { 
        q: "Was ist ein 'Moke'?", 
        a: "Eine Eidechse, die nach Belieben schrumpfen kann",
        book: "Phantastische Tierwesen und wo sie zu finden sind",
        info: "Aufgrund ihrer Fähigkeit zu schrumpfen, werden Moke-Häute oft für Geldbeutel verwendet, die sich bei Annäherung von Dieben zusammenziehen."
    },
    { 
        q: "Wofür ist der 'Horklump' bekannt?", 
        a: "Er ist ein fleischiger Pilz, der Regenwürmer frisst",
        book: "Phantastische Tierwesen / Videospiele",
        info: "Horklumpe sind rosa, stachlig und gelten als Gartenschädlinge. Gnome essen sie gerne."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Tarantallegra'?", 
        a: "Die Beine des Opfers tanzen unkontrolliert",
        book: "Harry Potter und die Kammer des Schreckens",
        info: "Draco Malfoy wendet diesen Fluch im Duellierclub gegen Harry an, woraufhin Harrys Beine einen wilden Stepptanz aufführen."
    },
    { 
        q: "Was ist ein 'Quintaped'?", 
        a: "Ein gefährliches Tierwesen mit fünf behaarten Beinen",
        book: "Phantastische Tierwesen und wo sie zu finden sind",
        info: "Legenden besagen, dass die Quintapeds eigentlich verwandeltet Mitglieder des MacBoon-Clans von der Insel Drear sind."
    },
    { 
        q: "Was macht der Zauberspruch 'Glisseo'?", 
        a: "Er verwandelt eine Treppe in eine Rutsche",
        book: "Harry Potter und die Heiligtümer des Todes",
        info: "Hermine nutzt diesen Spruch während der Schlacht von Hogwarts, um Verfolger auf einer Treppe abzuschütteln."
    },
    { 
        q: "Was ist ein 'Kniesel'?", 
        a: "Ein katzenartiges Wesen, das verdächtige Personen aufspürt",
        book: "Harry Potter und der Gefangene von Askaban",
        info: "Hermines Kater Krummbein ist ein halber Kniesel, weshalb er sofort spürt, dass mit Krätze (Peter Pettigrew) etwas nicht stimmt."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Langlock'?", 
        a: "Er klebt die Zunge des Opfers am Gaumen fest",
        book: "Harry Potter und der Halbblutprinz",
        info: "Ein Zauber von Severus Snape (Halbblutprinz). Harry wendet ihn gegen Peeves und später gegen Argus Filch an."
    },
    { 
        q: "Was ist ein 'Plimpy'?", 
        a: "Ein runder Fisch mit zwei langen Beinen",
        book: "Harry Potter und die Heiligtümer des Todes",
        info: "Luna Lovegood erwähnt oft Plimpys. Um sie abzuwehren, soll man Gulping Plimpy Suppe essen oder sie verknoten."
    },
    { 
        q: "Wozu dient der Zauberspruch 'Avis'?", 
        a: "Er lässt kleine Vögel aus dem Zauberstab erscheinen",
        book: "Harry Potter und der Feuerkelch",
        info: "Mr. Ollivander prüft damit Viktor Krums Zauberstab. Hermine nutzt ihn später im 6. Teil, um Vögel auf Ron zu hetzen."
    },
    { 
        q: "Was ist ein 'Shrake'?", 
        a: "Ein Fisch, der mit Stacheln bedeckt ist",
        book: "Phantastische Tierwesen",
        info: "Man glaubt, er wurde von Zauberern erschaffen, um Muggel-Fischernetze zu zerstören, die in einem bestimmten Gebiet fischten."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Oppugno'?", 
        a: "Er lässt beschworene Gegenstände oder Tiere jemanden angreifen",
        book: "Harry Potter und der Halbblutprinz",
        info: "Hermine nutzt diesen Spruch in Kombination mit 'Avis', um einen Schwarm kleiner Vögel auf Ron Weasley zu hetzen."
    },
    { 
        q: "Was ist ein 'Fwooper'?", 
        a: "Ein Vogel, dessen Gesang Menschen in den Wahnsinn treibt",
        book: "Phantastische Tierwesen",
        info: "Deshalb werden Fwooper immer mit einem Schweigezauber verkauft. Ihre Federn sind sehr beliebt für Schreibfedern."
    },
    { 
        q: "Was macht der Zauberspruch 'Anapneo'?", 
        a: "Er befreit die Atemwege, wenn sich jemand verschluckt hat",
        book: "Harry Potter und der Halbblutprinz",
        info: "Professor Slughorn wendet diesen Zauber bei Marcus Belby an, als dieser sich beim Essen im 'Slug-Club' verschluckt."
    },
    { 
        q: "Was ist ein 'Billywig'?", 
        a: "Ein Insekt, dessen Stich Schwebezustände verursacht",
        book: "Phantastische Tierwesen",
        info: "Junge australische Zauberer versuchen oft, sich stechen zu lassen, um die Nebenwirkung des Schwebens zu genießen. Bestandteil von 'Zischenden Wissbies'."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Defodio'?", 
        a: "Er gräbt oder meißelt Löcher in Stein und Erde",
        book: "Harry Potter und die Heiligtümer des Todes",
        info: "Harry, Ron und Hermine nutzen ihn, um aus den Tunneln von Gringotts zu entkommen, indem sie den Tunnel vergrößern."
    },
    { 
        q: "Was ist ein 'Murtlap'?", 
        a: "Ein rattenartiges Wesen mit einem Gewächs auf dem Rücken",
        book: "Harry Potter und der Orden des Phönix",
        info: "Hermine legt Harrys Hand in Murtlap-Essenz ein, nachdem Umbridge ihn gezwungen hat, 'Ich soll keine Lügen erzählen' in seine Hand zu ritzen."
    },
    { 
        q: "Was passiert beim Zauberspruch 'Episkey'?", 
        a: "Er heilt kleinere Verletzungen wie gebrochene Nasen",
        book: "Harry Potter und der Halbblutprinz",
        info: "Tonks (im Buch) bzw. Luna (im Film) heilt damit Harrys Nase, nachdem Draco Malfoy ihm im Hogwarts-Express ins Gesicht getreten hat."
    },
    { 
        q: "Was ist ein 'Nundu'?", 
        a: "Ein riesiger Leopard, dessen Atem tödliche Seuchen bringt",
        book: "Phantastische Tierwesen",
        info: "Er gilt als eines der gefährlichsten Tierwesen überhaupt. Um ihn zu bändigen, sind oft über 100 Zauberer nötig."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Erecto'?", 
        a: "Er baut Zeltstrukturen oder ähnliches automatisch auf",
        book: "Harry Potter und die Heiligtümer des Todes",
        info: "Hermine und Harry benutzen diesen Spruch auf ihrer Flucht oft, um ihr Zelt schnell aufzubauen."
    },
    { 
        q: "Was ist ein 'Pogrebin'?", 
        a: "Ein russischer Gnom, der Menschen verfolgt und Verzweiflung bringt",
        book: "Phantastische Tierwesen",
        info: "Er sieht aus wie ein grauer Stein. Er folgt Menschen, bis diese vor Verzweiflung zusammenbrechen, und versucht sie dann zu fressen."
    },
    { 
        q: "Was macht der Zauberspruch 'Ferula'?", 
        a: "Er bandagiert und schient gebrochene Gliedmaßen",
        book: "Harry Potter und der Gefangene von Askaban",
        info: "Lupin wendet diesen Zauber bei Ron an, um dessen gebrochenes Bein in der Heulenden Hütte zu schienen."
    },
    { 
        q: "Was ist ein 'Ramora'?", 
        a: "Ein Fisch, der Schiffe ankern kann",
        book: "Phantastische Tierwesen",
        info: "Der Ramora ist ein silberner Fisch, der Schiffe in Gewässern festhalten kann. Er steht unter dem Schutz der Internationalen Zauberervereinigung."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Incarcerous'?", 
        a: "Er fesselt das Opfer mit dicken Seilen",
        book: "Harry Potter und der Orden des Phönix",
        info: "Umbridge setzt diesen Zauber gegen die Zentauren im Verbotenen Wald ein, was diese extrem wütend macht."
    },
    { 
        q: "Was ist ein 'Streeler'?", 
        a: "Eine Riesenschnecke, die eine ätzende Schleimspur hinterlässt",
        book: "Harry Potter und die Kammer des Schreckens (Spiel/Buch)",
        info: "Ihr Schleim ist so giftig, dass er Pflanzen vernichtet. Sie wird oft als Haustier gehalten, muss aber ständig das Terrarium wechseln."
    },
    { 
        q: "Was macht der Zauberspruch 'Obscuro'?", 
        a: "Er verbindet dem Opfer die Augen mit einer Binde",
        book: "Harry Potter und die Heiligtümer des Todes",
        info: "Hermine wendet ihn auf das Porträt von Phineas Nigellus Black an, damit er ihren Aufenthaltsort nicht ausspionieren kann."
    },
    { 
        q: "Was ist ein 'Tebo'?", 
        a: "Ein Warzenschwein, das sich unsichtbar machen kann",
        book: "Phantastische Tierwesen",
        info: "Seine Haut wird oft für Schutzschilde und Kleidung verwendet, da sie sehr widerstandsfähig ist."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Piertotum Locomotor'?", 
        a: "Er erweckt Statuen und Rüstungen zum Leben",
        book: "Harry Potter und die Heiligtümer des Todes",
        info: "Professor McGonagall nutzt diesen Zauber, um die Statuen von Hogwarts zur Verteidigung der Schule in den Kampf zu schicken."
    },
    { 
        q: "Was ist ein 'Jobberknoll'?", 
        a: "Ein Vogel, der erst beim Sterben alle gehörten Geräusche rückwärts abspielt",
        book: "Phantastische Tierwesen",
        info: "Seine Federn werden für Wahrheitselixiere und Gedächtnistränke verwendet."
    },
    { 
        q: "Was macht der Zauberspruch 'Rictusempra'?", 
        a: "Er verursacht unkontrollierbaren Kitzelreiz",
        book: "Harry Potter und die Kammer des Schreckens",
        info: "Harry nutzt ihn im Duellierclub gegen Draco Malfoy. Im Film schleudert er Draco nur weg, im Buch bekommt er einen Lachanfall."
    },
    { 
        q: "Was ist ein 'Lobalug'?", 
        a: "Ein Meereswesen, das Angreifer mit Gift bespritzt",
        book: "Phantastische Tierwesen",
        info: "Wird vom Meeresvolk als Waffe genutzt. Sein Giftbeutel wird für Zaubertränke verwendet."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Serpensortia'?", 
        a: "Er lässt eine Schlange aus dem Zauberstab erscheinen",
        book: "Harry Potter und die Kammer des Schreckens",
        info: "Draco Malfoy nutzt diesen Spruch im Duell gegen Harry, was dazu führt, dass Harry seine Parsel-Fähigkeiten offenbart."
    },
    { 
        q: "Was ist ein 'Mondkalb'?", 
        a: "Ein scheues Wesen, das bei Vollmond komplexe Tänze aufführt",
        book: "Phantastische Tierwesen",
        info: "Die geometrischen Muster, die sie in Kornfelder tanzen, verwirren Muggel oft (Kornkreise)."
    },
    { 
        q: "Was macht der Zauberspruch 'Tergeo'?", 
        a: "Er saugt Flüssigkeiten oder Staub weg",
        book: "Harry Potter und der Halbblutprinz",
        info: "Hermine säubert damit Harrys Gesicht von Blut, nachdem Draco ihm im Zug die Nase gebrochen hat."
    },
    { 
        q: "Was ist ein 'Clabbert'?", 
        a: "Ein baumbewohnendes Wesen, dessen Pustel bei Gefahr rot leuchtet",
        book: "Phantastische Tierwesen",
        info: "Amerikanische Zauberer hielten sie früher in Gärten, um vor Muggeln gewarnt zu werden."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Melofors'?", 
        a: "Er steckt den Kopf des Opfers in einen Kürbis",
        book: "Harry Potter Videospiele / Prisoner of Azkaban",
        info: "Ein eher humorvoller Fluch, der den Kopf des Gegners komplett in einen Kürbis hüllt."
    },
    { 
        q: "Was ist ein 'Bundimun'?", 
        a: "Ein pilzartiges Wesen, das Häuser verrotten lässt",
        book: "Phantastische Tierwesen",
        info: "Man erkennt sie am fauligen Gestank. Ihr Sekret wird (verdünnt) in einigen magischen Reinigungsmitteln verwendet."
    },
    { 
        q: "Was macht der Zauberspruch 'Mobiliarbus'?", 
        a: "Er bewegt Bäume oder hölzerne Objekte",
        book: "Harry Potter und der Gefangene von Askaban",
        info: "Hermine verschiebt damit einen Weihnachtsbaum im 'Drei Besen', um Harry vor den Lehrern zu verstecken."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Duro'?", 
        a: "Er verwandelt Objekte in festen Stein",
        book: "Harry Potter und die Heiligtümer des Todes",
        info: "Hermine nutzt ihn, um einen Wandteppich in Stein zu verwandeln, damit zwei Todesser dagegen prallen."
    },
    { 
        q: "Was ist ein 'Nogschwanz'?", 
        a: "Ein Dämon in Ferkelgestalt, der schwer zu fangen ist",
        book: "Phantastische Tierwesen",
        info: "Sie schleichen sich in Schweineställe und säugen an normalen Säuen. Ein reinweißer Hund ist nötig, um sie zu vertreiben."
    },
    { 
        q: "Was macht der Zauberspruch 'Specialis Revelio'?", 
        a: "Er enthüllt verborgene magische Eigenschaften eines Objekts",
        book: "Harry Potter und der Halbblutprinz",
        info: "Hermine wendet ihn auf das Buch des Halbblutprinzen an, um zu prüfen, ob es verflucht ist."
    },
    { 
        q: "Was ist ein 'Porlock'?", 
        a: "Ein pferdeartiger Hüter von Pferdeherden",
        book: "Phantastische Tierwesen",
        info: "Sie sind scheu, haben eine große Nase und gehen auf zwei Hufen. Sie bewachen Pferde vor Gefahren."
    },
    { 
        q: "Was bewirkt der Zauberspruch 'Quietus'?", 
        a: "Er macht eine magisch verstärkte Stimme wieder normal leise",
        book: "Harry Potter und der Feuerkelch",
        info: "Ludo Bagman nutzt diesen Spruch nach dem Quidditch-WM-Finale, um seine Stimme nach dem Kommentar wieder zu senken."
    },
    { 
        q: "Was ist ein 'Re‘em'?", 
        a: "Ein goldener Ochse, dessen Blut enorme Stärke verleiht",
        book: "Phantastische Tierwesen",
        info: "Das Blut ist extrem selten und auf dem Schwarzmarkt sehr teuer. Wer es trinkt, wird für kurze Zeit immens stark."
    }
];

export const QUESTIONS: Record<string, { q: string, a: string }[]> = {
  harry_potter: HP_QUESTIONS,
  words: [
    { q: "Was ist ein 'Aglet'?", a: "Plastikhülle am Ende des Schnürsenkels" },
    { q: "Was bezeichnet man als 'Philtrum'?", a: "Rinne zwischen Nase und Oberlippe" },
    { q: "Was ist ein 'Zarf'?", a: "Papphalter für heiße Kaffeebecher" },
    { q: "Was versteht man unter 'Petrichor'?", a: "Geruch von Regen auf trockener Erde" },
    { q: "Was ist ein 'Tittle'?", a: "Der Punkt über dem i oder j" },
    { q: "Was bezeichnet der Begriff 'Dysania'?", a: "Unfähigkeit, morgens aufzustehen" },
    { q: "Was ist ein 'Glabella'?", a: "Stelle zwischen den Augenbrauen" },
    { q: "Was versteht man unter 'Paresthesie'?", a: "Kribbeln bei eingeschlafenen Körperteilen" },
    { q: "Was ist ein 'Vagitus'?", a: "Erster Schrei eines Neugeborenen" },
    { q: "Was bezeichnet das Wort 'Apricity'?", a: "Wärme der Wintersonne" },
    { q: "Was ist ein 'Snollygoster'?", a: "Politiker ohne feste Prinzipien" },
    { q: "Was versteht man unter 'Defenestration'?", a: "Wurf aus dem Fenster" },
    { q: "Was bezeichnet der Begriff 'Collywobbles'?", a: "Flaues Gefühl im Magen" },
    { q: "Was versteht man unter 'Punt'?", a: "Wölbung im Boden einer Weinflasche" },
    { q: "Was bezeichnet 'Gowpen'?", a: "Schale aus zwei hohlen Händen" },
    { q: "Was bezeichnet der Begriff 'Quincunx'?", a: "Fünf-Punkte-Anordnung wie auf Würfeln" },
    { q: "Was ist ein 'Wamble'?", a: "Gurgelndes Geräusch im Bauch" },
    { q: "Was bezeichnet 'Zenzizenzizenzic'?", a: "Die achte Potenz einer Zahl" },
    { q: "Was versteht man unter 'Bibliosmie'?", a: "Geruch von alten Büchern" },
    { q: "Was ist 'Tarantismus'?", a: "Der unbändige Drang zu tanzen" },
    { q: "Was ist ein 'Mumpsimus'?", a: "Festhalten an einem Fehler" },
    { q: "Was ist ein 'Borborygmus'?", a: "Das Knurren des Magens" },
    { q: "Was bezeichnet 'Horripilation'?", a: "Das Aufstellen der Nackenhaare" },
    { q: "Was versteht man unter 'Lethologica'?", a: "Wort liegt auf der Zunge, fällt aber nicht ein" },
    { q: "Was bezeichnet 'Clinomania'?", a: "Der Wunsch, im Bett zu bleiben" },
    { q: "Was bedeutet 'Pandiculation'?", a: "Strecken und Gähnen beim Aufwachen" },
    { q: "Was bezeichnet 'Tsundoku'?", a: "Bücher kaufen und ungelesen stapeln" },
    { q: "Was ist eine 'Anatidaephobie'?", a: "Angst, von einer Ente beobachtet zu werden" },
    { q: "Was ist eine 'Arachibutyrophobie'?", a: "Angst vor Erdnussbutter am Gaumen" },
    { q: "Was ist eine 'Hippopotomonstrosesquippedaliophobie'?", a: "Angst vor langen Wörtern" },
    { q: "Was ist eine 'Pogonophobie'?", a: "Angst vor Bärten" },
    { q: "Was ist eine 'Turophobie'?", a: "Angst vor Käse" },
    { q: "Was ist eine 'Omphalophobie'?", a: "Angst vor Bauchnabeln" },
    { q: "Was ist eine 'Koumpounophobie'?", a: "Angst vor Knöpfen an Kleidung" },
    { q: "Was ist eine 'Pentheraphobie'?", a: "Angst vor der Schwiegermutter" },
    { q: "Was ist eine 'Ablutophobie'?", a: "Angst vor dem Waschen oder Baden" },
    { q: "Was ist eine 'Ergophobie'?", a: "Angst vor Arbeit" },
    { q: "Was ist eine 'Cherophobie'?", a: "Angst vor Fröhlichkeit oder Glück" },
    { q: "Was ist eine 'Geniophobie'?", a: "Angst vor Kinne(n)" },
    { q: "Was ist eine 'Linonophobie'?", a: "Angst vor Schnüren oder Bindfäden" },
    { q: "Was ist eine 'Nomophobie'?", a: "Angst, ohne Mobiltelefon zu sein" },
    { q: "Was ist eine 'Barophobie'?", a: "Angst vor der Schwerkraft" },
    { q: "Was ist eine 'Eisoptrophobie'?", a: "Angst vor Spiegeln" },
    { q: "Was ist eine 'Papaphobie'?", a: "Angst vor dem Papst" },
    { q: "Was ist eine 'Allodoxaphobie'?", a: "Angst vor Meinungen" },
    { q: "Was ist eine 'Geliophobie'?", a: "Angst vor dem Lachen" },
    { q: "Was ist eine 'Phobophobie'?", a: "Angst vor der Angst" },
    { q: "Was ist eine 'Pteronophobie'?", a: "Angst vor Federn" },
    { q: "Was versteht man unter 'Pareidolie'?", a: "Gesichter in leblosen Objekten erkennen" },
    { q: "Was ist eine 'Lemniskate'?", a: "Das mathematische Symbol für Unendlichkeit" },
    { q: "Was sind 'Phosphene'?", a: "Lichtmuster, die man sieht, wenn man die Augen reibt" },
    { q: "Was ist ein 'Interrobang'?", a: "Ein Satzzeichen, das Frage- und Ausrufezeichen kombiniert (?!)." },
    { q: "Was bedeutet 'Griffonnage'?", a: "Unleserliche oder schlampige Handschrift" },
    { q: "Was ist eine 'Hexakosioihexekontahexaphobie'?", a: "Angst vor der Zahl 666" },
    { q: "Was ist eine 'Anuptaphobie'?", a: "Angst, für immer Single zu bleiben" },
    { q: "Was ist eine 'Trypophobie'?", a: "Angst vor Ansammlungen kleiner Löcher" },
    { q: "Was ist eine 'Coulrophobie'?", a: "Angst vor Clowns" },
    { q: "Was bezeichnet 'Crapulence'?", a: "Krankheitsgefühl nach übermäßigem Essen oder Trinken" },
    { q: "Was ist ein 'Mondegreen'?", a: "Ein verhörter Liedtext, der den Sinn verändert" },
    { q: "Was ist ein 'Spoonerismus'?", a: "Unabsichtlicher Vertausch von Anfangsbuchstaben (Schüttelreim)" },
    { q: "Was ist ein 'Semordnilap'?", a: "Wort, das rückwärts ein anderes Wort ergibt" },
    { q: "Was bedeutet 'Callipygian'?", a: "Ein wohlgeformtes Gesäß habend" },
    { q: "Was ist der 'Omphalos'?", a: "Der Bauchnabel" },
    { q: "Was bedeutet 'Barmecide'?", a: "Illusionäre Fülle, die enttäuscht" },
    { q: "Was bedeutet 'Canoodle'?", a: "Zärtlich kuscheln oder knutschen" },
    { q: "Was bedeutet 'Discombobulate'?", a: "Jemanden völlig verwirren" },
    { q: "Was bedeutet 'Flummox'?", a: "Jemanden ratlos machen" },
    { q: "Was ist ein 'Kerfuffle'?", a: "Ein unnötiges Durcheinander oder Aufruhr" },
    { q: "Was bedeutet 'Lollygag'?", a: "Trödeln oder Zeit verschwenden" },
    { q: "Was bedeutet 'Malarkey'?", a: "Unsinn oder Quatsch" },
    { q: "Was ist ein 'Nincompoop'?", a: "Ein Dummkopf oder Narr" },
    { q: "Was bedeutet 'Shenanigans'?", a: "Schelmerei oder Unfug" },
    { q: "Was bedeutet 'Skedaddle'?", a: "Hastig weglaufen" },
    { q: "Was bedeutet 'Bamboozle'?", a: "Jemanden täuschen oder verblüffen" },
    { q: "Was ist ein 'Bibliophiler'?", a: "Ein Liebhaber von Büchern" },
    { q: "Was ist ein 'Logophiler'?", a: "Ein Liebhaber von Wörtern" },
    { q: "Was ist ein 'Pluviophiler'?", a: "Jemand, der Regen liebt" },
    { q: "Was ist eine 'Nyctophilie'?", a: "Liebe zur Nacht oder Dunkelheit" },
    { q: "Was ist ein 'Selenophiler'?", a: "Jemand, der den Mond liebt" },
    { q: "Was ist ein 'Thalassophiler'?", a: "Jemand, der das Meer liebt" },
    { q: "Was ist ein 'Ailurophiler'?", a: "Ein Katzenliebhaber" },
    { q: "Was ist ein 'Cynophiler'?", a: "Ein Hundeliebhaber" },
    { q: "Was ist eine 'Mysophobie'?", a: "Angst vor Schmutz oder Keimen" },
    { q: "Was ist eine 'Acrophobie'?", a: "Höhenangst" },
    { q: "Was ist eine 'Agoraphobie'?", a: "Angst vor weiten Plätzen oder Menschenmengen" },
    { q: "Was ist eine 'Claustrophobie'?", a: "Angst vor engen Räumen" },
    { q: "Was ist eine 'Aerophobie'?", a: "Flugangst" },
    { q: "Was ist eine 'Glossophobie'?", a: "Angst vor öffentlichem Sprechen" }
  ],
  laws: [
    { q: "Was ist auf deutschen Autobahnen streng verboten?", a: "Anhalten wegen Benzinmangels" },
    { q: "Welches Geräusch ist in Schweizer Mietshäusern nach 22 Uhr oft verboten?", a: "Toilettenspülung betätigen" },
    { q: "Was darf man in Florida legalerweise nicht an eine Parkuhr binden?", a: "Einen Elefanten" },
    { q: "Welchen Namen darf ein Schwein in Frankreich per Gesetz nicht tragen?", a: "Napoleon" },
    { q: "In welcher speziellen Kleidung darf man das britische Parlament nicht betreten?", a: "Ritterrüstung" },
    { q: "Welches familiäre Ereignis zu vergessen gilt in Samoa als Straftat?", a: "Geburtstag der Ehefrau" },
    { q: "Welche Pflicht haben Schotten gegenüber Fremden, die an ihre Tür klopfen?", a: "Toilettennutzung erlauben" },
    { q: "Der Import welcher Ware ist in Singapur strikt untersagt?", a: "Kaugummi" },
    { q: "Welche Tiere darf man auf dem Markusplatz in Venedig nicht füttern?", a: "Tauben" },
    { q: "Welche drakonische Strafe droht in Arizona für das Fällen eines Kaktus?", a: "Bis zu 25 Jahre Haft" },
    { q: "Was ist in Oklahoma im Umgang mit Hunden gesetzlich verboten?", a: "Grimassen schneiden" },
    { q: "Welche Bekleidungsvorschrift gilt in Thailand beim Verlassen des Hauses?", a: "Unterwäsche-Pflicht" },
    { q: "Was ist in Portugal am Strand streng verboten?", a: "Urinieren ins Meer" },
    { q: "Was ist in Victoria (Australien) verboten, wenn man kein Elektriker ist?", a: "Glühbirne wechseln" },
    { q: "In welcher Stadt ist es verboten, im Auto zu küssen, während es fährt?", a: "Eboli (Italien)" },
    { q: "Was ist im britischen Parlament streng verboten?", a: "Dort zu sterben" },
    { q: "Was ist in der Stadt Chico in Kalifornien verboten?", a: "Atomwaffen zu zünden" },
    { q: "Was ist in der Schweiz sonntags verboten zu tun?", a: "Wäsche aufhängen" },
    { q: "Was ist in Mailand gesetzlich vorgeschrieben, außer bei Beerdigungen?", a: "Zu lächeln" },
    { q: "Was ist in Alabama verboten, in der Gesäßtasche zu tragen?", a: "Eine Eistüte" },
    { q: "Was ist in Baltimore, Maryland, verboten mit ins Kino zu nehmen?", a: "Einen Löwen" },
    { q: "Was ist in Frankreich verboten, auf Bahnsteigen zu tun?", a: "Sich zu küssen" },
    { q: "Was ist in Minnesota verboten, auf dem Kopf zu tragen?", a: "Ein Huhn" },
    { q: "Was ist in North Carolina verboten, wenn man Bingo spielt?", a: "Länger als 5 Stunden spielen" },
    { q: "Was ist in Texas verboten, vom zweiten Stock eines Hotels zu schießen?", a: "Büffel" },
    { q: "Was ist in Singapur verboten, in der Öffentlichkeit zu tun?", a: "Nackt herumlaufen" },
    { q: "Was ist in Venedig verboten, an Brücken anzubringen?", a: "Liebesschlösser" },
    { q: "Was ist in Eraclea (Italien) am Strand verboten?", a: "Sandburgen bauen" },
    { q: "Was ist in Großbritannien verboten, mit einer Briefmarke zu tun?", a: "Kopfstehend aufkleben" },
    { q: "Was ist in Sarpourenx (Frankreich) verboten?", a: "Auf dem Friedhof zu sterben" },
    { q: "Was ist in Capri verboten zu tragen?", a: "Klappernde Holzschuhe" },
    { q: "Was ist in Barbados verboten zu tragen?", a: "Tarnkleidung" },
    { q: "Was ist in Athen auf antiken Stätten verboten?", a: "High Heels tragen" },
    { q: "Was ist in Rom verboten, auf der Spanischen Treppe zu tun?", a: "Essen" },
    { q: "Was ist in Florenz in der Nähe von Kirchen verboten?", a: "Essen" },
    { q: "Was ist in San Francisco verboten, mit Tauben zu tun?", a: "Füttern" }
  ],
  facts: [
    { q: "Was war der ursprüngliche Verwendungszweck von Luftpolsterfolie?", a: "Sie sollte eine 3D-Tapete sein" },
    { q: "Was passiert mit dem Eiffelturm im Sommer?", a: "Er wird bis zu 15 cm größer" },
    { q: "Was ist historisch überraschend an der Universität Oxford?", a: "Sie ist älter als das Aztekenreich" },
    { q: "Wofür wurde Ketchup in den 1830er Jahren verkauft?", a: "Als Medizin gegen Durchfall" },
    { q: "Was produzierte Nintendo bei der Gründung im Jahr 1889?", a: "Handbemalte Spielkarten" },
    { q: "Was ist das Besondere an der Flagge von Nepal?", a: "Sie ist nicht rechteckig" },
    { q: "Was war der erste 'Computer-Bug' tatsächlich?", a: "Eine echte Motte im Relais" },
    { q: "Was ist das Besondere am Herzschlag eines Blauwals?", a: "Man hört ihn 3 Kilometer weit" },
    { q: "Was geschah im kürzesten Krieg der Geschichte zwischen Sansibar und Großbritannien?", a: "Er endete nach 38 Minuten" },
    { q: "Warum wurden High Heels ursprünglich erfunden?", a: "Für persische Reiter, um fest im Sattel zu stehen" },
    { q: "Was ist das Einzigartige an der Mona Lisa?", a: "Sie hat keine Augenbrauen" },
    { q: "Was ist überraschend an der Herkunft des Wortes 'Roboter'?", a: "Es kommt aus dem Tschechischen und bedeutet Zwangsarbeit" },
    { q: "Was passiert, wenn man eine Weintraube in die Mikrowelle legt?", a: "Sie erzeugt Plasma" },
    { q: "Was war an den ersten Trailern für den Film 'Star Wars' besonders?", a: "Sie hatten keine Spezialeffekte" },
    { q: "Was ist der eigentliche Zweck der kleinen Tasche in Jeans?", a: "Für Taschenuhren gedacht" },
    { q: "Was ist das Besondere an der Anordnung der Buchstaben auf einer Tastatur (QWERTY)?", a: "Sie sollte das Tippen verlangsamen" },
    { q: "Was ist die chemische Besonderheit von Gold?", a: "Es rostet niemals" },
    { q: "Was passiert in Longyearbyen (Norwegen), wenn jemand stirbt?", a: "Man darf dort nicht beerdigt werden" },
    { q: "Was war das erste Produkt, das jemals einen Barcode hatte?", a: "Eine Packung Kaugummi" },
    { q: "Was ist das Besondere an der Form von Wombat-Kot?", a: "Er ist würfelförmig" },
    { q: "Was ist die überraschende Wahrheit über die Hautfarbe eines Eisbären?", a: "Die Haut ist schwarz" },
    { q: "Wie schaffen es Delfine, während des Schlafs nicht zu ertrinken?", a: "Eine Gehirnhälfte bleibt wach" },
    { q: "Was ist das Erstaunliche an Honig aus ägyptischen Gräbern?", a: "Er ist noch essbar" },
    { q: "Welchen ungewöhnlichen militärischen Rang bekleidet ein Pinguin in Schottland?", a: "Ehrenoberst der Garde" },
    { q: "Was ist anatomisch besonders am Oktopus?", a: "Er hat drei Herzen" },
    { q: "Warum halten Seeotter beim Schlafen Händchen?", a: "Damit sie in der Strömung nicht abtreiben" },
    { q: "Was ist die eigentliche Farbe von Nilpferd-Schweiß?", a: "Er ist rötlich" },
    { q: "Wer ist laut Stückzahl der größte Reifenhersteller der Welt?", a: "LEGO" },
    { q: "Was ist das offizielle Nationaltier von Schottland?", a: "Das Einhorn" },
    { q: "Was wurde eher erfunden: Das Feuerzeug oder Streichhölzer?", a: "Das Feuerzeug" },
    { q: "Was ist das Besondere an Bananen in Bezug auf Radioaktivität?", a: "Sie sind leicht radioaktiv wegen Kalium" },
    { q: "Woraus bestand der Klebstoff der ersten Briefmarken?", a: "Aus Knochenleim" },
    { q: "Was ist das Besondere an der Nationalhymne von Spanien?", a: "Sie hat keinen Text" },
    { q: "Was war ursprünglich der Hauptzweck von Coca-Cola?", a: "Ein Mittel gegen Kopfschmerzen und Müdigkeit" },
    { q: "Wie viele Menschen leben im Vatikanstaat (Staatsbürger)?", a: "Weniger als 1000" },
    { q: "Was ist das Besondere an der Rotation der Venus?", a: "Sie dreht sich im Uhrzeigersinn" },
    { q: "Was war das teuerste Gewürz im Mittelalter?", a: "Safran" },
    { q: "Was ist der eigentliche Name der 'Barbie'-Puppe?", a: "Barbara Millicent Roberts" },
    { q: "Was ist das Besondere an der Zunge einer Giraffe?", a: "Sie ist dunkelblau gegen Sonnenbrand" },
    { q: "Was ist der einzige Buchstabe, der nicht im Periodensystem vorkommt?", a: "J" },
    { q: "Woraus besteht der Staub in deinem Haus größtenteils?", a: "Aus abgestorbenen Hautschuppen" },
    { q: "Was ist die Besonderheit an Wolken?", a: "Sie wiegen bis zu 500 Tonnen" },
    { q: "Was passiert, wenn man heißes Wasser einfriert im Vergleich zu kaltem?", a: "Heißes Wasser gefriert schneller" },
    { q: "Wer erfand die Zuckerwatte?", a: "Ein Zahnarzt" },
    { q: "Wofür wurde die Kettensäge ursprünglich erfunden?", a: "Als Geburtshilfe" },
    { q: "Was ist zeitlich näher am Bau der Pyramiden: Das iPhone oder Kleopatra?", a: "Das iPhone" },
    { q: "Wo wollte der Erfinder der Pringles-Dose beerdigt werden?", a: "In einer Pringles-Dose" },
    { q: "Was können Faultiere länger als Delfine?", a: "Die Luft anhalten" },
    { q: "Was können Kühe mit Treppen tun?", a: "Hochgehen, aber nicht runter" },
    { q: "Was haben Koalas mit Menschen gemeinsam?", a: "Einzigartige Fingerabdrücke" },
    { q: "Woran wachsen Cashewkerne?", a: "Unten an einem 'Cashew-Apfel'" },
    { q: "Was passierte in Frankreich im selben Jahr, als 'Star Wars' ins Kino kam?", a: "Die letzte Guillotine-Hinrichtung" },
    { q: "Welcher US-Bundesstaat liegt Afrika am nächsten?", a: "Maine" },
    { q: "Was ist größer: Die Oberfläche von Pluto oder Russland?", a: "Russland" },
    { q: "Was importiert Saudi-Arabien aus Australien?", a: "Kamele" },
    { q: "Welches Geräusch machen Geparden anstatt zu brüllen?", a: "Sie miauen" },
    { q: "Wie hieß Google ursprünglich?", a: "BackRub" },
    { q: "Warum wurde Fanta in Deutschland erfunden?", a: "Coca-Cola Sirup fehlte im 2. Weltkrieg" },
    { q: "Was lebte zeitlich näher am T-Rex: Der Stegosaurus oder wir?", a: "Wir Menschen" },
    { q: "Wonach riecht es angeblich im Weltraum?", a: "Nach verbranntem Steak" },
    { q: "Wer hat mehr Knochen: Ein Baby oder ein Erwachsener?", a: "Ein Baby" },
    { q: "Was sind Erdbeeren botanisch gesehen?", a: "Nüsse (Sammelnussfrucht)" },
    { q: "Womit schmecken Schmetterlinge?", a: "Mit ihren Füßen" },
    { q: "Wie können manche Schildkröten atmen?", a: "Durch ihren Hintern" },
    { q: "Wie viele Päpste leben statistisch gesehen auf einem Quadratkilometer im Vatikan?", a: "Mehr als zwei" },
    { q: "Was trugen Wikingerhelme in Wahrheit nie?", a: "Hörner" },
    { q: "Was ist für Vögel giftig, aber für uns gesund?", a: "Avocados" },
    { q: "Wie viele Gehirne hat ein Oktopus?", a: "Neun" },
    { q: "Was ist älter: Haie oder Bäume?", a: "Haie" },
    { q: "Warum hatte die Titanic-Crew keine Ferngläser?", a: "Der Schlüssel zum Schrank fehlte" },
    { q: "Was können Schweine anatomisch nicht tun?", a: "In den Himmel schauen" }
  ],
  traditions: [
    { q: "Was machen die Bewohner von Castrillo de Murcia mit ihren Neugeborenen?", a: "Männer springen über sie" },
    { q: "Was ist der Zweck des 'Affen-Buffets' in Lopburi?", a: "Affen werden mit Obst gefüttert" },
    { q: "Was passiert in Schottland beim 'Blackening' vor einer Hochzeit?", a: "Paar wird mit Dreck beworfen" },
    { q: "Welches Ritual vollziehen junge Sateré-Mawé für das Erwachsensein?", a: "Handschuhe voller Ameisen tragen" },
    { q: "Was tun Menschen in Dänemark am 25. Geburtstag von Unverheirateten?", a: "Zimt-Dusche für das Geburtstagskind" },
    { q: "Was ist die Besonderheit beim 'Cheese-Rolling' in England?", a: "Käserad-Jagd den Hügel hinunter" },
    { q: "Was werfen sich die Bewohner von Ivrea beim Karneval an den Kopf?", a: "Schlacht mit Orangen" },
    { q: "Was machen die Menschen in Panama mit Papp-Puppen zu Neujahr?", a: "Feierliches Verbrennen" },
    { q: "Was passiert beim 'Naghol'-Ritual auf Vanuatu?", a: "Turmsprung mit Lianen-Sicherung" },
    { q: "Was macht der 'Caga Tió' in Katalonien an Weihnachten?", a: "Er scheidet Geschenke aus" },
    { q: "Was ist der 'National Sleepy Head Day' in Finnland?", a: "Der letzte Schläfer wird ins Wasser geworfen" },
    { q: "Was passiert beim 'Tomatina'-Fest in Spanien?", a: "Massenschlacht mit Tomaten" },
    { q: "Was machen die Menschen in Oaxaca (Mexiko) am 23. Dezember?", a: "Skulpturen aus Radieschen schnitzen" },
    { q: "Was ist der 'Groundhog Day' in den USA?", a: "Ein Murmeltier sagt das Wetter vorher" },
    { q: "Was machen die Menschen in Wales mit einem Pferdeschädel?", a: "Mari Lwyd Umzug" },
    { q: "Was ist das 'Cooper's Hill Cheese-Rolling'?", a: "Rennen hinter einem Käselaib her" },
    { q: "Was machen die Menschen in Japan beim 'Kanamara Matsuri'?", a: "Penis-Festival feiern" },
    { q: "Was passiert beim 'Up Helly Aa' in Schottland?", a: "Ein Wikingerschiff wird verbrannt" },
    { q: "Was ist 'Takanakuy' in Peru?", a: "Faustkämpfe an Weihnachten um Streit zu klären" },
    { q: "Was wird beim 'Eukonkanto' in Finnland gemacht?", a: "Männer tragen ihre Ehefrauen durch Parcours" },
    { q: "Was ist 'Setsubun' in Japan?", a: "Bohnen werfen um Dämonen zu vertreiben" },
    { q: "Was passiert beim 'Famadihana' auf Madagaskar?", a: "Leichen werden ausgegraben und tanzen" },
    { q: "Was ist der 'Rouketopolemos' in Griechenland?", a: "Raketenkrieg zwischen zwei Kirchen" },
    { q: "Was machen Männer beim 'Onbashira' in Japan?", a: "Auf riesigen Baumstämmen einen Hügel runterrutschen" },
    { q: "Was passiert beim 'Las Bolas de Fuego' in El Salvador?", a: "Menschen werfen Feuerbälle aufeinander" },
    { q: "Was ist das 'Boryeong' Festival in Südkorea?", a: "Eine riesige Schlammschlacht" },
    { q: "Was wird beim 'Gurning' Wettbewerb in England gemacht?", a: "Möglichst hässliche Grimassen schneiden" },
    { q: "Was wird traditionell beim 'Polterabend' in Deutschland gemacht?", a: "Porzellan zerschlagen für Glück" },
    { q: "Was wird beim 'Sechseläuten' in Zürich verbrannt?", a: "Ein Schneemann voller Sprengstoff (Böögg)" },
    { q: "Was ist 'Hanal Pixan' in Mexiko?", a: "Essen für die Seelen der Verstorbenen kochen" },
    { q: "Was passiert beim 'Krampuslauf' in Österreich?", a: "Dämonen erschrecken Passanten mit Ruten" },
    { q: "Was ist die 'Fiesta de Santa Marta de Ribarteme' in Spanien?", a: "Lebende Menschen werden in Särgen getragen" },
    { q: "Was ist 'Bog Snorkelling' in Wales?", a: "Wettkampf im Schnorcheln durch einen schlammigen Moorgraben" },
    { q: "Was passiert beim 'Worm Charming' in England?", a: "Würmer durch Vibrationen aus der Erde locken" },
    { q: "Was ist 'Camel Wrestling' in der Türkei?", a: "Ein traditioneller Ringkampf zwischen zwei Kamelen" },
    { q: "Was wird beim 'Yanvalou' in Haiti getan?", a: "Ein Vodou-Tanz mit wellenartigen Bewegungen" },
    { q: "Was ist 'Ganna' in Äthiopien?", a: "Eine extrem harte Variante von Hockey an Weihnachten" },
    { q: "Was passiert am 'Nyepi'-Tag auf Bali?", a: "Tag der absoluten Stille: Kein Licht, kein Lärm, kein Feuer" },
    { q: "Was ist 'Suigan' in Japan?", a: "Traditionelles Kormoranfischen bei Nacht mit Feuer" },
    { q: "Was ist 'Bikini Skiing' in Sibirien?", a: "Skifahren in Badekleidung bei Minusgraden als Rekordversuch" },
    { q: "Was passiert beim 'Baby Crying Sumo' in Japan?", a: "Zwei Babys treten an: Wer zuerst weint, gewinnt" },
    { q: "Was ist 'Antzar Eguna' im Baskenland?", a: "Wettbewerb, bei dem man einer Gans (heute Gummi) den Kopf abreißt" }
  ],
  slogans: [
    { q: "Wie lautet der Slogan von: Ricola?", a: "Wer hat's erfunden" },
    { q: "Wie lautet der Slogan von: Alpecin?", a: "Doping für die Haare" },
    { q: "Wie lautet der Slogan von: Skoda?", a: "Simply Clever" },
    { q: "Wie lautet der Slogan von: Bausparkasse Schwäbisch Hall?", a: "Auf diese Steine können Sie bauen" },
    { q: "Wie lautet der Slogan von: LBS?", a: "Wir geben Ihrer Zukunft ein Zuhause" },
    { q: "Wie lautet der Slogan von: Paulaner?", a: "Gut, besser, Paulaner" },
    { q: "Wie lautet der Slogan von: Mon Chéri?", a: "Wer kann dazu schon nein sagen" },
    { q: "Wie lautet der Slogan von: Bärenmarke?", a: "Nichts geht über Bärenmarke" },
    { q: "Wie lautet der Slogan von: Toffifee?", a: "Es steckt viel Spaß in Toffifee" },
    { q: "Wie lautet der Slogan von: Hornbach?", a: "Es gibt immer was zu tun" },
    { q: "Wie lautet der Slogan von: Persil?", a: "Da weiß man, was man hat" },
    { q: "Wie lautet der Slogan von: Seitenbacher?", a: "Lecker, lecker, lecker" },
    { q: "Wie lautet der Slogan von: Clausthaler?", a: "Alles andere ist nur Bier" },
    { q: "Wie lautet der Slogan von: Iglo?", a: "Iss was Gscheits" },
    { q: "Wie lautet der Slogan von: Sparkasse?", a: "Wenn's um Geld geht" },
    { q: "Wie lautet der Slogan von: Volksbanken Raiffeisenbanken?", a: "Wir machen den Weg frei" },
    { q: "Wie lautet der Slogan von: Visa?", a: "Die Freiheit nehm ich mir" },
    { q: "Wie lautet der Slogan von: Allianz?", a: "Hoffentlich Allianz versichert" },
    { q: "Wie lautet der Slogan von: Rügenwalder Mühle?", a: "Deftig, kräftig, würzig, gut" },
    { q: "Wie lautet der Slogan von: Ergo?", a: "Versichern heißt verstehen" },
    { q: "Wie lautet der Slogan von: Toyota?", a: "Nichts ist unmöglich" },
    { q: "Wie lautet der Slogan von: Leibniz?", a: "Nur echt mit den 52 Zähnen" },
    { q: "Wie lautet der Slogan von: HB?", a: "Wer wird denn gleich in die Luft gehen" },
    { q: "Wie lautet der Slogan von: Gelbe Seiten?", a: "Vielleicht hätten Sie jemanden fragen sollen, der sich damit auskennt" },
    { q: "Wie lautet der Slogan von: Schöfferhofer Weizen?", a: "Das prickelt so schön in meinem Bauchnabel" },
    { q: "Wie lautet der Slogan von: Milka?", a: "Die zarteste Versuchung, seit es Schokolade gibt" },
    { q: "Wie lautet der Slogan von: BMW?", a: "Freude am Fahren" },
    { q: "Wie lautet der Slogan von: Audi?", a: "Vorsprung durch Technik" },
    { q: "Wie lautet der Slogan von: Krombacher?", a: "Eine Perle der Natur" },
    { q: "Wie lautet der Slogan von: Ratiopharm?", a: "Gute Preise. Gute Besserung." },
    { q: "Wie lautet der Slogan von: Zott Sahnejoghurt?", a: "Hinein ins Weekend-Feeling" },
    { q: "Wie lautet der Slogan von: Mastercard?", a: "Unbezahlbar" },
    { q: "Wie lautet der Slogan von: Ford?", a: "Die tun was" },
    { q: "Wie lautet der Slogan von: Meister Proper?", a: "Putzt so sauber, dass man sich drin spiegeln kann" },
    { q: "Wie lautet der Slogan von: Dr. Oetker?", a: "Qualität ist das beste Rezept" },
    { q: "Wie lautet der Slogan von: Duplo?", a: "Die wahrscheinlich längste Praline der Welt" },
    { q: "Wie lautet der Slogan von: Müller Milchreis?", a: "Wenn der kleine Hunger kommt" },
    { q: "Wie lautet der Slogan von: Wick Blau?", a: "Da atmen Sie auf" },
    { q: "Wie lautet der Slogan von: Miele?", a: "Immer besser" },
    { q: "Wie lautet der Slogan von: Mars?", a: "Und du schmeckst die Lebenslust" },
    { q: "Wie lautet der Slogan von: Apollo Optik?", a: "Da wackelt nix" },
    { q: "Wie lautet der Slogan von: Check24?", a: "Hier check ich alles" },
    { q: "Wie lautet der Slogan von: Deutsche Bahn?", a: "Diese Zeit gehört Dir" },
    { q: "Wie lautet der Slogan von: Rewe?", a: "Dein Markt" },
    { q: "Wie lautet der Slogan von: Obi?", a: "Wie, wo, was weiß Obi" },
    { q: "Wie lautet der Slogan von: Douglas?", a: "Come in and find out" },
    { q: "Wie lautet der Slogan von: Kellogg's Frosties?", a: "Die wecken den Tiger in dir" },
    { q: "Wie lautet der Slogan von: Biskin?", a: "Schließt den Saft im Braten ein" },
    { q: "Wie lautet der Slogan von: Bluna?", a: "Sind wir nicht alle ein bisschen Bluna?" },
    { q: "Wie lautet der Slogan von: Drei Wetter Taft?", a: "Berlin, Windstärke 5. Das Haar sitzt." },
    { q: "Wie lautet der Slogan von: Asbach Uralt?", a: "Im Asbach Uralt ist der Geist des Weines" },
    { q: "Wie lautet der Slogan von: Batida de Coco?", a: "Der Kuss der Kokosnuss" },
    { q: "Wie lautet der Slogan von: Fruchtzwerge?", a: "So wertvoll wie ein kleines Steak" },
    { q: "Wie lautet der Slogan von: Gard?", a: "Schönes Haar ist dir gegeben, lass es leben mit Gard" },
    { q: "Wie lautet der Slogan von: Kuschelweich?", a: "Gibt Ihrer Wäsche den frischen Duft" },
    { q: "Wie lautet der Slogan von: Perwoll?", a: "Ist das neu? Nein, mit Perwoll gewaschen" },
    { q: "Wie lautet der Slogan von: Odol?", a: "Für sympathischen Atem" },
    { q: "Wie lautet der Slogan von: Teekanne?", a: "Macht den Tee" },
    { q: "Wie lautet der Slogan von: Spee?", a: "Die schlaue Art zu waschen" },
    { q: "Wie lautet der Slogan von: Underberg?", a: "Komm doch mit auf den Underberg" },
    { q: "Wie lautet der Slogan von: Mövenpick?", a: "Der kleine Luxus für jeden Tag" },
    { q: "Wie lautet der Slogan von: König Pilsener?", a: "Heute ein König" },
    { q: "Wie lautet der Slogan von: Melitta?", a: "Macht Kaffee zum Genuss" },
    { q: "Wie lautet der Slogan von: Mentos?", a: "The Freshmaker" },
    { q: "Wie lautet der Slogan von: Merci?", a: "Merci, dass es dich gibt" },
    { q: "Wie lautet der Slogan von: Mezzo Mix?", a: "Cola küsst Orange" },
    { q: "Wie lautet der Slogan von: Mirácoli?", a: "Mirácoli ist fertig!" },
    { q: "Wie lautet der Slogan von: Nimm2?", a: "Vitamine und Naschen" },
    { q: "Wie lautet der Slogan von: Pringles?", a: "Einmal gepoppt, nie mehr gestoppt" },
    { q: "Wie lautet der Slogan von: Rama?", a: "Macht das Frühstück gut" },
    { q: "Wie lautet der Slogan von: Somat?", a: "Für Geschirr wie neu" },
    { q: "Wie lautet der Slogan von: Sprite?", a: "Folge deinem Durst" },
    { q: "Wie lautet der Slogan von: Tic Tac?", a: "Die Erfrischung mit dem Dreh" },
    { q: "Wie lautet der Slogan von: Twix?", a: "Raider heißt jetzt Twix" },
    { q: "Wie lautet der Slogan von: Vernel?", a: "Ein Hauch von Frische" },
    { q: "Wie lautet der Slogan von: Volvic?", a: "Erfrischt dein Leben" },
    { q: "Wie lautet der Slogan von: Whiskas?", a: "Katzen würden Whiskas kaufen" },
    { q: "Wie lautet der Slogan von: Wrigleys Extra?", a: "Essen, Trinken, Kauen" },
    { q: "Wie lautet der Slogan von: Wüstenrot?", a: "Wohnen heißt Wüstenrot" },
    { q: "Wie lautet der Slogan von: Zentis?", a: "Zentis – Aus Liebe zur Frucht" },
    { q: "Wie lautet der Slogan von: Landliebe?", a: "Liebe ist, wenn es Landliebe ist" },
    { q: "Wie lautet der Slogan von: Dacia?", a: "Das Statussymbol für alle, die kein Statussymbol brauchen" },
    { q: "Wie lautet der Slogan von: BVG?", a: "Weil wir dich lieben" },
    { q: "Wie lautet der Slogan von: Astra?", a: "Was dagegen?" },
    { q: "Wie lautet der Slogan von: Flensburger?", a: "Das flenst" },
    { q: "Wie lautet der Slogan von: Lieferando?", a: "Hör auf deinen Bauch" },
    { q: "Wie lautet der Slogan von: Parship?", a: "Alle 11 Minuten verliebt sich ein Single" },
    { q: "Wie lautet der Slogan von: ElitePartner?", a: "Für Akademiker und Singles mit Niveau" },
    { q: "Wie lautet der Slogan von: Trivago?", a: "Hotel? Trivago" },
    { q: "Wie lautet der Slogan von: Klarna?", a: "Smoooth Shopping" },
    { q: "Wie lautet der Slogan von: Oatly?", a: "Wow no cow" },
    { q: "Wie lautet der Slogan von: Ehrmann?", a: "Keiner macht mich mehr an" },
    { q: "Wie lautet der Slogan von: Exquisa?", a: "Keiner schmeckt mir so wie dieser" },
    { q: "Wie lautet der Slogan von: Deichmann?", a: "Weil wir Schuhe lieben" },
    { q: "Wie lautet der Slogan von: Airbnb?", a: "Belong anywhere" },
    { q: "Wie lautet der Slogan von: Subway?", a: "Eat Fresh" },
    { q: "Wie lautet der Slogan von: Skittles?", a: "Taste the Rainbow" },
    { q: "Wie lautet der Slogan von: LG?", a: "Life's Good" },
    { q: "Wie lautet der Slogan von: Nokia?", a: "Connecting People" },
    { q: "Wie lautet der Slogan von: Frosch?", a: "Für Mensch und Umwelt" },
    { q: "Wie lautet der Slogan von: Katjes?", a: "Jes Jes Jes" },
    { q: "Wie lautet der Slogan von: HelloFresh?", a: "Einfach besser essen" },
    { q: "Wie lautet der Slogan von: FlixBus?", a: "Fahr grün" },
    { q: "Wie lautet der Slogan von: Vinted?", a: "Mach es zu deinem neuen Lieblingsteil" },
    { q: "Wie lautet der Slogan von: Carglass?", a: "Carglass repariert, Carglass tauscht aus" },
    { q: "Wie lautet der Slogan von: Thalia?", a: "Entdecke neue Seiten" },
    { q: "Wie lautet der Slogan von: Sennheiser?", a: "The Pursuit of Perfect Sound" },
    { q: "Wie lautet der Slogan von: Kärcher?", a: "Makes a difference" },
    { q: "Wie lautet der Slogan von: Jägermeister?", a: "Wer, wenn nicht wir." },
    { q: "Wie lautet der Slogan von: Ur-Krostitzer?", a: "Wahre Helden stehen mitten im Leben" },
    { q: "Wie lautet der Slogan von: Fisherman's Friend?", a: "Sind sie zu stark, bist du zu schwach" },
    { q: "Wie lautet der Slogan von: Aoste?", a: "Entdecke die Aoste-Seite des Lebens" },
    { q: "Wie lautet der Slogan von: Almdudler?", a: "Wenn die kan Almdudler hab'n, geh' i wieder ham" },
    { q: "Wie lautet der Slogan von: Bosch?", a: "Technik fürs Leben" },
    { q: "Wie lautet der Slogan von: Manner?", a: "Mag man eben" },
    { q: "Wie lautet der Slogan von: Snickers?", a: "Du bist nicht du, wenn du hungrig bist" },
    { q: "Wie lautet der Slogan von: Beton?", a: "Es kommt darauf an, was man draus macht" },
    { q: "Wie lautet der Slogan von: Bauknecht?", a: "Bauknecht weiß, was Frauen wünschen" },
    { q: "Wie lautet der Slogan von: AEG?", a: "Aus Erfahrung Gut" },
    { q: "Wie lautet der Slogan von: Deutsche Bundesbahn?", a: "Alle reden vom Wetter. Wir nicht." },
    { q: "Wie lautet der Slogan von: Palmolive?", a: "Sie baden gerade Ihre Hände darin" },
    { q: "Wie lautet der Slogan von: Ariel?", a: "Nicht nur sauber, sondern rein" },
    { q: "Wie lautet der Slogan von: Kaba?", a: "Der Plantagentrank" },
    { q: "Wie lautet der Slogan von: Ajax?", a: "Der weiße Wirbelwind" },
    { q: "Wie lautet der Slogan von: Der General?", a: "Den Schmutz packt der General" },
    { q: "Wie lautet der Slogan von: Domestos?", a: "Tötet alle bekannten Keime" },
    { q: "Wie lautet der Slogan von: Warsteiner?", a: "Das einzig Wahre" },
    { q: "Wie lautet der Slogan von: Diebels?", a: "Ein schöner Tag" },
    { q: "Wie lautet der Slogan von: Jacobs Krönung?", a: "Die Krönung des Kaffeegenusses" },
    { q: "Wie lautet der Slogan von: Fa?", a: "Die wilde Frische von Limonen" },
    { q: "Wie lautet der Slogan von: Apollinaris?", a: "The Queen of Table Waters" },
    { q: "Wie lautet der Slogan von: IKEA?", a: "Wohnst du noch oder lebst du schon?" },
    { q: "Wie lautet der Slogan von: Red Bull?", a: "Verleiht Flüüügel" },
    { q: "Wie lautet der Slogan von: Media Markt?", a: "Ich bin doch nicht blöd" },
    { q: "Wie lautet der Slogan von: Saturn?", a: "Geiz ist geil" },
    { q: "Wie lautet der Slogan von: Ritter Sport?", a: "Quadratisch. Praktisch. Gut." },
    { q: "Wie lautet der Slogan von: Haribo?", a: "Macht Kinder froh und Erwachsene ebenso" },
    { q: "Wie lautet der Slogan von: Kinder Überraschung?", a: "Spannung, Spiel und Schokolade" },
    { q: "Wie lautet der Slogan von: Netto?", a: "Dann geh doch zu Netto!" },
    { q: "Wie lautet der Slogan von: L'Oréal?", a: "Weil ich es mir wert bin" },
    { q: "Wie lautet der Slogan von: Maybelline?", a: "Vielleicht ist sie geboren. Vielleicht ist es Maybelline." },
    { q: "Wie lautet der Slogan von: Gillette?", a: "Für das Beste im Mann" },
    { q: "Wie lautet der Slogan von: KitKat?", a: "Have a break, have a KitKat" },
    { q: "Wie lautet der Slogan von: Edeka?", a: "Wir lieben Lebensmittel" },
    { q: "Wie lautet der Slogan von: fritz-kola?", a: "Vielviel Koffein" },
    { q: "Wie lautet der Slogan von: Werther's Echte?", a: "Weil du etwas Besonderes bist" }
  ],
  jobs: [
    { q: "Was ist ein 'Zeidler'?", a: "Ein mittelalterlicher Wald-Imker, der Honig von wilden Bienen sammelte" },
    { q: "Was macht ein 'Oshiya'?", a: "Er drückt in Japan Fahrgäste professionell in überfüllte U-Bahnen" },
    { q: "Was ist ein 'Pechsieder'?", a: "Ein historischer Handwerker, der aus Nadelholz Teer und Pech herstellte" },
    { q: "Was versteht man unter einem 'Abtrittanbieter'?", a: "Jemand, der Passanten gegen Geld einen mobilen Eimer als Toilette anbot" },
    { q: "Was ist ein 'Bierschrotter'?", a: "Ein Arbeiter, der schwere Bierfässer in tiefe Brauereikeller transportierte" },
    { q: "Was ist die Aufgabe eines 'Hühner-Sexers'?", a: "Er bestimmt das Geschlecht von frisch geschlüpften Küken in Sekundenschnelle" },
    { q: "Was bezeichnet man als 'Säckler'?", a: "Ein spezialisierter Lederhandwerker, der Lederhosen und Beutel fertigt" },
    { q: "Was war ein 'Kiepenträger'?", a: "Ein Lastenträger, der Waren in großen Rückenkörben über Gebirgspfade transportierte" },
    { q: "Was ist ein 'Ameisler'?", a: "Jemand, der Ameisenpuppen im Wald sammelte, um sie als Tierfutter zu verkaufen" },
    { q: "Was macht ein 'Putzmacher'?", a: "Ein spezialisierter Handwerker, der Damenhüte entwirft und anfertigt" },
    { q: "Was ist ein 'Groschengräber'?", a: "Ein Arbeiter, der per Hand Brunnen reinigte oder Abwasserkanäle von Schlamm befreite" },
    { q: "Was macht ein 'Mollenhauer'?", a: "Er fertigt aus Holzstämmen Mulden, Backtröge und Waschwannen an" },
    { q: "Was ist ein 'Posamentierer'?", a: "Ein Hersteller von Zierbesätzen wie Kordeln, Quasten und Fransen für Kleidung" },
    { q: "Was versteht man unter einem 'Riemer'?", a: "Ein Lederhandwerker, der Riemen für Pferdegeschirre und Sättel herstellte" },
    { q: "Was ist ein 'Blaudrucker'?", a: "Ein Spezialist für die Stoffveredelung mit einem Reserveverfahren und Indigoblau" },
    { q: "Was macht ein 'Katzenschläger'?", a: "Ein Arbeiter in der alten Textilindustrie, der Wolle mit einem Bogen auflockerte" },
    { q: "Was war die Aufgabe eines 'Vogelstellers'?", a: "Ein professioneller Vogelfänger, der Singvögel für den Verkauf fing" },
    { q: "Was macht ein 'Lector' in einer kubanischen Zigarrenfabrik?", a: "Er liest den Arbeitern während der Produktion Zeitungen oder Romane vor" },
    { q: "Was ist die Aufgabe eines 'Baqueano' in Argentinien?", a: "Ein Fährtensucher, der den Weg durch Wildnis allein an Naturzeichen findet" },
    { q: "Was ist eine 'Ama' in Japan?", a: "Eine traditionelle Taucherin, die ohne Atemgerät nach Perlen und Muscheln sucht" },
    { q: "Was macht ein 'Dabbawala' in Indien?", a: "Er transportiert in einem komplexen System Brotdosen von Wohnungen in Büros" },
    { q: "Was ist ein 'Seringueiro' in Brasilien?", a: "Ein Sammler, der im Regenwald die Gummibäume für Latex anzapft" },
    { q: "Was macht ein 'Fumista' in Italien?", a: "Ein Handwerker für den Bau und Rauchabzug von Kachelöfen" },
    { q: "Was ist ein 'Gomero' in Lateinamerika?", a: "Ein Mechaniker, der ausschließlich Reifenpannen flickt" },
    { q: "Was war ein 'Munshi' in Indien?", a: "Ein Sprachlehrer oder Sekretär für Ausländer" },
    { q: "Was macht ein 'Zanjero' im Südwesten der USA?", a: "Ein Wasseraufseher, der manuell Bewässerungsschleusen regelt" },
    { q: "Was macht ein 'Bodger' in England?", a: "Ein wandernder Drechsler, der direkt im Wald Stuhlbeine fertigt" },
    { q: "Was ist ein 'Aboyeur'?", a: "Ein Küchenmitarbeiter, der die Bestellungen an die Köche ausruft" },
    { q: "Was macht ein 'Dondurmacı'?", a: "Ein türkischer Eisverkäufer, der Kunden mit akrobatischen Tricks neckt" },
    { q: "Was ist ein 'Chicha-Brauer' in Peru?", a: "Er kaut Mais und spuckt ihn zur Fermentierung in einen Topf" },
    { q: "Was macht ein 'Fledermaus-Guano-Sammler'?", a: "Er sammelt in Höhlen Fledermauskot als wertvollen Dünger" },
    { q: "Was ist ein 'Topeiro' in Portugal?", a: "Ein professioneller Maulwurfsfänger auf Golfplätzen" },
    { q: "Was macht ein 'Supa-Supa' in Japan?", a: "Er kühlt in Gängen wartende Leute mit riesigen Fächern" },
    { q: "Was ist ein 'Knocker-up'?", a: "Ein historischer Weckdienst, der mit Stöcken an Fenster klopfte" },
    { q: "Was macht ein 'Putter' im Bergbau?", a: "Er schiebt schwere Kohlewagen durch engste Minengänge" },
    { q: "Was ist ein 'Tosher'?", a: "Jemand, der in Abwasserkanälen nach Wertsachen suchte" },
    { q: "Was ist ein 'Mudlark'?", a: "Jemand, der im Schlamm von Flussufern nach Verwertbarem suchte" },
    { q: "Was machte ein 'Fuller'?", a: "Er reinigte Wolltuch, indem er darauf in Urin herumtrampelte" },
    { q: "Was war die Aufgabe eines 'Gong Farmer'?", a: "Er schaufelte nachts die Fäkalien aus Plumpsklos" },
    { q: "Was ist ein 'Knacker'?", a: "Jemand, der alte Tierkadaver zu Seife und Leim verarbeitet" },
    { q: "Was macht ein 'Redsmith'?", a: "Ein Kupferschmied (wegen der rötlichen Farbe des Metalls)" },
    { q: "Was war die Aufgabe eines 'Puddler'?", a: "Er rührte geschmolzenes Eisen um, um Unreinheiten zu entfernen" },
    { q: "Was ist ein 'Chandler'?", a: "Ein Kerzenmacher und Schiffsausrüster" },
    { q: "Was macht ein 'Fletcher'?", a: "Er fertigt Pfeile an und befestigt die Federn" },
    { q: "Was ist ein 'Cordwainer'?", a: "Ein Schuhmacher, der nur neues Leder verarbeitet" },
    { q: "Was war ein 'Scrivener'?", a: "Ein professioneller Schreiber oder Kopist für Dokumente" },
    { q: "Was macht ein 'Ostler'?", a: "Er kümmert sich in einem Gasthof um die Pferde der Gäste" },
    { q: "Was ist ein 'Costermonger'?", a: "Ein Straßenhändler, der Obst und Gemüse verkauft" },
    { q: "Was verkauft ein 'Haberdasher'?", a: "Kleinkram für Näherei (Knöpfe, Bänder) und Herrenmode" },
    { q: "Was macht ein 'Milliner'?", a: "Er entwirft und fertigt Hüte an" },
    { q: "Was war die Aufgabe eines 'Linkboy'?", a: "Er trug nachts eine Fackel, um Fußgängern den Weg zu leuchten" },
    { q: "Was ist ein 'Resurrectionist'?", a: "Ein Leichendieb, der Körper für medizinische Studien ausgrub" }
  ]
};
