
export const CATEGORIES = [
  { id: 'words', name: 'Wörter', icon: 'BookOpen' },
  { id: 'laws', name: 'Kuriose Gesetze', icon: 'Gavel' },
  { id: 'facts', name: 'Fun Facts', icon: 'Sparkles' },
  { id: 'traditions', name: 'Kuriose Bräuche', icon: 'Globe' },
  { id: 'slogans', name: 'Werbeslogans', icon: 'Megaphone' },
  { id: 'jobs', name: 'Kuriose Berufe', icon: 'Briefcase' }
];

export const QUESTIONS: Record<string, { q: string, a: string }[]> = {
  words: [
    { q: "Was ist ein 'Aglet'?", a: "Plastikhülle am Ende des Schnürsenkels" },
    { q: "Was bezeichnet man als 'Philtrum'?", a: "Rinne zwischen Nase und Oberlippe" },
    { q: "Was ist ein 'Zarf'?", a: "Papphalter für heiße Kaffeebecher" },
    { q: "Was versteht man unter 'Petrichor'?", a: "Geruch von Regen auf trockener Erde" },
    { q: "Was ist ein 'Tittle'?", a: "Der Punkt über dem i oder j" },
    { q: "Was bezeichnet der Begriff 'Dysania'?", a: "Unfähigkeit, morgens aufzustehen" },
    { q: "Was ist ein 'Glabella'?", a: "Stelle zwischen den Augenbrauen" },
    { q: "Was versteht man unter 'Paresthesie'?", a: "Kribbeln bei eingeschlafenen Körperteilen" },
    { q: "Was ist ein 'Vagitus'?", a: "Erster Schrei eines Neugeborenen" },
    { q: "Was bezeichnet das Wort 'Apricity'?", a: "Wärme der Wintersonne" },
    { q: "Was ist ein 'Snollygoster'?", a: "Politiker ohne feste Prinzipien" },
    { q: "Was versteht man unter 'Defenestration'?", a: "Wurf aus dem Fenster" },
    { q: "Was bezeichnet der Begriff 'Collywobbles'?", a: "Flaues Gefühl im Magen" },
    { q: "Was versteht man unter 'Punt'?", a: "Wölbung im Boden einer Weinflasche" },
    { q: "Was bezeichnet 'Gowpen'?", a: "Schale aus zwei hohlen Händen" },
    { q: "Was bezeichnet der Begriff 'Quincunx'?", a: "Fünf-Punkte-Anordnung wie auf Würfeln" },
    { q: "Was ist ein 'Wamble'?", a: "Gurgelndes Geräusch im Bauch" },
    { q: "Was bezeichnet 'Zenzizenzizenzic'?", a: "Die achte Potenz einer Zahl" },
    { q: "Was versteht man unter 'Bibliosmie'?", a: "Geruch von alten Büchern" },
    { q: "Was ist 'Tarantismus'?", a: "Der unbändige Drang zu tanzen" },
    { q: "Was ist ein 'Mumpsimus'?", a: "Festhalten an einem Fehler" },
    { q: "Was ist ein 'Borborygmus'?", a: "Das Knurren des Magens" },
    { q: "Was bezeichnet 'Horripilation'?", a: "Das Aufstellen der Nackenhaare" },
    { q: "Was versteht man unter 'Lethologica'?", a: "Wort liegt auf der Zunge, fällt aber nicht ein" },
    { q: "Was bezeichnet 'Clinomania'?", a: "Der Wunsch, im Bett zu bleiben" },
    { q: "Was bedeutet 'Pandiculation'?", a: "Strecken und Gähnen beim Aufwachen" },
    { q: "Was bezeichnet 'Tsundoku'?", a: "Bücher kaufen und ungelesen stapeln" },
    { q: "Was ist eine 'Anatidaephobie'?", a: "Angst, von einer Ente beobachtet zu werden" },
    { q: "Was ist eine 'Arachibutyrophobie'?", a: "Angst vor Erdnussbutter am Gaumen" },
    { q: "Was ist eine 'Hippopotomonstrosesquippedaliophobie'?", a: "Angst vor langen Wörtern" },
    { q: "Was ist eine 'Pogonophobie'?", a: "Angst vor Bärten" },
    { q: "Was ist eine 'Turophobie'?", a: "Angst vor Käse" },
    { q: "Was ist eine 'Omphalophobie'?", a: "Angst vor Bauchnabeln" },
    { q: "Was ist eine 'Koumpounophobie'?", a: "Angst vor Knöpfen an Kleidung" },
    { q: "Was ist eine 'Pentheraphobie'?", a: "Angst vor der Schwiegermutter" },
    { q: "Was ist eine 'Ablutophobie'?", a: "Angst vor dem Waschen oder Baden" },
    { q: "Was ist eine 'Ergophobie'?", a: "Angst vor Arbeit" },
    { q: "Was ist eine 'Cherophobie'?", a: "Angst vor Fröhlichkeit oder Glück" },
    { q: "Was ist eine 'Geniophobie'?", a: "Angst vor Kinne(n)" },
    { q: "Was ist eine 'Linonophobie'?", a: "Angst vor Schnüren oder Bindfäden" },
    { q: "Was ist eine 'Nomophobie'?", a: "Angst, ohne Mobiltelefon zu sein" },
    { q: "Was ist eine 'Barophobie'?", a: "Angst vor der Schwerkraft" },
    { q: "Was ist eine 'Eisoptrophobie'?", a: "Angst vor Spiegeln" },
    { q: "Was ist eine 'Papaphobie'?", a: "Angst vor dem Papst" },
    { q: "Was ist eine 'Allodoxaphobie'?", a: "Angst vor Meinungen" },
    { q: "Was ist eine 'Geliophobie'?", a: "Angst vor dem Lachen" },
    { q: "Was ist eine 'Phobophobie'?", a: "Angst vor der Angst" },
    { q: "Was ist eine 'Pteronophobie'?", a: "Angst vor Federn" }
  ],
  laws: [
    { q: "Was ist auf deutschen Autobahnen streng verboten?", a: "Anhalten wegen Benzinmangels" },
    { q: "Welches Geräusch ist in Schweizer Mietshäusern nach 22 Uhr oft verboten?", a: "Toilettenspülung betätigen" },
    { q: "Was darf man in Florida legalerweise nicht an eine Parkuhr binden?", a: "Einen Elefanten" },
    { q: "Welchen Namen darf ein Schwein in Frankreich per Gesetz nicht tragen?", a: "Napoleon" },
    { q: "In welcher speziellen Kleidung darf man das britische Parlament nicht betreten?", a: "Ritterrüstung" },
    { q: "Welches familiäre Ereignis zu vergessen gilt in Samoa als Straftat?", a: "Geburtstag der Ehefrau" },
    { q: "Welche Pflicht haben Schotten gegenüber Fremden, die an ihre Tür klopfen?", a: "Toilettennutzung erlauben" },
    { q: "Der Import welcher Ware ist in Singapur strikt untersagt?", a: "Kaugummi" },
    { q: "Welche Tiere darf man auf dem Markusplatz in Venedig nicht füttern?", a: "Tauben" },
    { q: "Welche drakonische Strafe droht in Arizona für das Fällen eines Kaktus?", a: "Bis zu 25 Jahre Haft" },
    { q: "Was ist in Oklahoma im Umgang mit Hunden gesetzlich verboten?", a: "Grimassen schneiden" },
    { q: "Welche Bekleidungsvorschrift gilt in Thailand beim Verlassen des Hauses?", a: "Unterwäsche-Pflicht" },
    { q: "Was ist in Portugal am Strand streng verboten?", a: "Urinieren ins Meer" },
    { q: "Was ist in Victoria (Australien) verboten, wenn man kein Elektriker ist?", a: "Glühbirne wechseln" },
    { q: "In welcher Stadt ist es verboten, im Auto zu küssen, während es fährt?", a: "Eboli (Italien)" },
    { q: "Was ist im britischen Parlament streng verboten?", a: "Dort zu sterben" },
    { q: "Was ist in der Stadt Chico in Kalifornien verboten?", a: "Atomwaffen zu zünden" },
    { q: "Was ist in der Schweiz sonntags verboten zu tun?", a: "Wäsche aufhängen" },
    { q: "Was ist in Mailand gesetzlich vorgeschrieben, außer bei Beerdigungen?", a: "Zu lächeln" },
    { q: "Was ist in Alabama verboten, in der Gesäßtasche zu tragen?", a: "Eine Eistüte" },
    { q: "Was ist in Baltimore, Maryland, verboten mit ins Kino zu nehmen?", a: "Einen Löwen" },
    { q: "Was ist in Frankreich verboten, auf Bahnsteigen zu tun?", a: "Sich zu küssen" },
    { q: "Was ist in Minnesota verboten, auf dem Kopf zu tragen?", a: "Ein Huhn" },
    { q: "Was ist in North Carolina verboten, wenn man Bingo spielt?", a: "Länger als 5 Stunden spielen" },
    { q: "Was ist in Texas verboten, vom zweiten Stock eines Hotels zu schießen?", a: "Büffel" },
    { q: "Was ist in Singapur verboten, in der Öffentlichkeit zu tun?", a: "Nackt herumlaufen" },
    { q: "Was ist in Venedig verboten, an Brücken anzubringen?", a: "Liebesschlösser" },
    { q: "Was ist in Eraclea (Italien) am Strand verboten?", a: "Sandburgen bauen" },
    { q: "Was ist in Großbritannien verboten, mit einer Briefmarke zu tun?", a: "Kopfstehend aufkleben" },
    { q: "Was ist in Sarpourenx (Frankreich) verboten?", a: "Auf dem Friedhof zu sterben" },
    { q: "Was ist in Capri verboten zu tragen?", a: "Klappernde Holzschuhe" },
    { q: "Was ist in Barbados verboten zu tragen?", a: "Tarnkleidung" },
    { q: "Was ist in Athen auf antiken Stätten verboten?", a: "High Heels tragen" },
    { q: "Was ist in Rom verboten, auf der Spanischen Treppe zu tun?", a: "Essen" },
    { q: "Was ist in Florenz in der Nähe von Kirchen verboten?", a: "Essen" },
    { q: "Was ist in San Francisco verboten, mit Tauben zu tun?", a: "Füttern" }
  ],
  facts: [
    { q: "Was war der ursprüngliche Verwendungszweck von Luftpolsterfolie?", a: "Sie sollte eine 3D-Tapete sein" },
    { q: "Was passiert mit dem Eiffelturm im Sommer?", a: "Er wird bis zu 15 cm größer" },
    { q: "Was ist historisch überraschend an der Universität Oxford?", a: "Sie ist älter als das Aztekenreich" },
    { q: "Wofür wurde Ketchup in den 1830er Jahren verkauft?", a: "Als Medizin gegen Durchfall" },
    { q: "Was produzierte Nintendo bei der Gründung im Jahr 1889?", a: "Handbemalte Spielkarten" },
    { q: "Was ist das Besondere an der Flagge von Nepal?", a: "Sie ist nicht rechteckig" },
    { q: "Was war der erste 'Computer-Bug' tatsächlich?", a: "Eine echte Motte im Relais" },
    { q: "Was ist das Besondere am Herzschlag eines Blauwals?", a: "Man hört ihn 3 Kilometer weit" },
    { q: "Was geschah im kürzesten Krieg der Geschichte zwischen Sansibar und Großbritannien?", a: "Er endete nach 38 Minuten" },
    { q: "Warum wurden High Heels ursprünglich erfunden?", a: "Für persische Reiter, um fest im Sattel zu stehen" },
    { q: "Was ist das Einzigartige an der Mona Lisa?", a: "Sie hat keine Augenbrauen" },
    { q: "Was ist überraschend an der Herkunft des Wortes 'Roboter'?", a: "Es kommt aus dem Tschechischen und bedeutet Zwangsarbeit" },
    { q: "Was passiert, wenn man eine Weintraube in die Mikrowelle legt?", a: "Sie erzeugt Plasma" },
    { q: "Was war an den ersten Trailern für den Film 'Star Wars' besonders?", a: "Sie hatten keine Spezialeffekte" },
    { q: "Was ist der eigentliche Zweck der kleinen Tasche in Jeans?", a: "Für Taschenuhren gedacht" },
    { q: "Was ist das Besondere an der Anordnung der Buchstaben auf einer Tastatur (QWERTY)?", a: "Sie sollte das Tippen verlangsamen" },
    { q: "Was ist die chemische Besonderheit von Gold?", a: "Es rostet niemals" },
    { q: "Was passiert in Longyearbyen (Norwegen), wenn jemand stirbt?", a: "Man darf dort nicht beerdigt werden" },
    { q: "Was war das erste Produkt, das jemals einen Barcode hatte?", a: "Eine Packung Kaugummi" },
    { q: "Was ist das Besondere an der Form von Wombat-Kot?", a: "Er ist würfelförmig" },
    { q: "Was ist die überraschende Wahrheit über die Hautfarbe eines Eisbären?", a: "Die Haut ist schwarz" },
    { q: "Wie schaffen es Delfine, während des Schlafs nicht zu ertrinken?", a: "Eine Gehirnhälfte bleibt wach" },
    { q: "Was ist das Erstaunliche an Honig aus ägyptischen Gräbern?", a: "Er ist noch essbar" },
    { q: "Welchen ungewöhnlichen militärischen Rang bekleidet ein Pinguin in Schottland?", a: "Ehrenoberst der Garde" },
    { q: "Was ist anatomisch besonders am Oktopus?", a: "Er hat drei Herzen" },
    { q: "Warum halten Seeotter beim Schlafen Händchen?", a: "Damit sie in der Strömung nicht abtreiben" },
    { q: "Was ist die eigentliche Farbe von Nilpferd-Schweiß?", a: "Er ist rötlich" },
    { q: "Wer ist laut Stückzahl der größte Reifenhersteller der Welt?", a: "LEGO" },
    { q: "Was ist das offizielle Nationaltier von Schottland?", a: "Das Einhorn" },
    { q: "Was wurde eher erfunden: Das Feuerzeug oder Streichhölzer?", a: "Das Feuerzeug" },
    { q: "Was ist das Besondere an Bananen in Bezug auf Radioaktivität?", a: "Sie sind leicht radioaktiv wegen Kalium" },
    { q: "Woraus bestand der Klebstoff der ersten Briefmarken?", a: "Aus Knochenleim" },
    { q: "Was ist das Besondere an der Nationalhymne von Spanien?", a: "Sie hat keinen Text" },
    { q: "Was war ursprünglich der Hauptzweck von Coca-Cola?", a: "Ein Mittel gegen Kopfschmerzen und Müdigkeit" },
    { q: "Wie viele Menschen leben im Vatikanstaat (Staatsbürger)?", a: "Weniger als 1000" },
    { q: "Was ist das Besondere an der Rotation der Venus?", a: "Sie dreht sich im Uhrzeigersinn" },
    { q: "Was war das teuerste Gewürz im Mittelalter?", a: "Safran" },
    { q: "Was ist der eigentliche Name der 'Barbie'-Puppe?", a: "Barbara Millicent Roberts" },
    { q: "Was ist das Besondere an der Zunge einer Giraffe?", a: "Sie ist dunkelblau gegen Sonnenbrand" },
    { q: "Was ist der einzige Buchstabe, der nicht im Periodensystem vorkommt?", a: "J" },
    { q: "Woraus besteht der Staub in deinem Haus größtenteils?", a: "Aus abgestorbenen Hautschuppen" },
    { q: "Was ist die Besonderheit an Wolken?", a: "Sie wiegen bis zu 500 Tonnen" },
    { q: "Was passiert, wenn man heißes Wasser einfriert im Vergleich zu kaltem?", a: "Heißes Wasser gefriert schneller" }
  ],
  traditions: [
    { q: "Was machen die Bewohner von Castrillo de Murcia mit ihren Neugeborenen?", a: "Männer springen über sie" },
    { q: "Was ist der Zweck des 'Affen-Buffets' in Lopburi?", a: "Affen werden mit Obst gefüttert" },
    { q: "Was passiert in Schottland beim 'Blackening' vor einer Hochzeit?", a: "Paar wird mit Dreck beworfen" },
    { q: "Welches Ritual vollziehen junge Sateré-Mawé für das Erwachsensein?", a: "Handschuhe voller Ameisen tragen" },
    { q: "Was tun Menschen in Dänemark am 25. Geburtstag von Unverheirateten?", a: "Zimt-Dusche für das Geburtstagskind" },
    { q: "Was ist die Besonderheit beim 'Cheese-Rolling' in England?", a: "Käserad-Jagd den Hügel hinunter" },
    { q: "Was werfen sich die Bewohner von Ivrea beim Karneval an den Kopf?", a: "Schlacht mit Orangen" },
    { q: "Was machen die Menschen in Panama mit Papp-Puppen zu Neujahr?", a: "Feierliches Verbrennen" },
    { q: "Was passiert beim 'Naghol'-Ritual auf Vanuatu?", a: "Turmsprung mit Lianen-Sicherung" },
    { q: "Was macht der 'Caga Tió' in Katalonien an Weihnachten?", a: "Er scheidet Geschenke aus" },
    { q: "Was ist der 'National Sleepy Head Day' in Finnland?", a: "Der letzte Schläfer wird ins Wasser geworfen" },
    { q: "Was passiert beim 'Tomatina'-Fest in Spanien?", a: "Massenschlacht mit Tomaten" },
    { q: "Was machen die Menschen in Oaxaca (Mexiko) am 23. Dezember?", a: "Skulpturen aus Radieschen schnitzen" },
    { q: "Was ist der 'Groundhog Day' in den USA?", a: "Ein Murmeltier sagt das Wetter vorher" },
    { q: "Was machen die Menschen in Wales mit einem Pferdeschädel?", a: "Mari Lwyd Umzug" },
    { q: "Was ist das 'Cooper's Hill Cheese-Rolling'?", a: "Rennen hinter einem Käselaib her" },
    { q: "Was machen die Menschen in Japan beim 'Kanamara Matsuri'?", a: "Penis-Festival feiern" },
    { q: "Was ist das 'Wife Carrying' in Finnland?", a: "Männer tragen Frauen über Hindernisse" },
    { q: "Was ist das 'Bog Snorkelling' in Wales?", a: "Schnorcheln im Moor" },
    { q: "Was ist das 'Toe Wrestling' in England?", a: "Ringen mit den Zehen" },
    { q: "Was ist das 'Air Guitar World Championships' in Finnland?", a: "Luftgitarre spielen" },
    { q: "Was ist das 'Baby Jumping' in Spanien?", a: "Über Babys springen" },
    { q: "Was ist das 'Monkey Buffet Festival' in Thailand?", a: "Buffet für Affen" },
    { q: "Was ist das 'Boryeong Mud Festival' in Südkorea?", a: "Schlammschlacht" },
    { q: "Was ist das 'Up Helly Aa' in Schottland?", a: "Wikinger-Feuerfestival" },
    { q: "Was ist das 'Lantern Festival' in Taiwan?", a: "Himmelslaternen steigen lassen" },
    { q: "Was ist das 'Holi Festival' in Indien?", a: "Farbenfest" },
    { q: "Was ist das 'Songkran Festival' in Thailand?", a: "Wasserschlacht" },
    { q: "Was ist das 'Dia de los Muertos' in Mexiko?", a: "Tag der Toten" },
    { q: "Was ist das 'Oktoberfest' in Deutschland?", a: "Bierfest" }
  ],
  slogans: [
    { q: "Wie lautet der Slogan von: Ricola?", a: "Wer hat's erfunden" },
    { q: "Wie lautet der Slogan von: Alpecin?", a: "Doping für die Haare" },
    { q: "Wie lautet der Slogan von: Skoda?", a: "Simply Clever" },
    { q: "Wie lautet der Slogan von: Bausparkasse Schwäbisch Hall?", a: "Auf diese Steine können Sie bauen" },
    { q: "Wie lautet der Slogan von: LBS?", a: "Wir geben Ihrer Zukunft ein Zuhause" },
    { q: "Wie lautet der Slogan von: Paulaner?", a: "Gut, besser, Paulaner" },
    { q: "Wie lautet der Slogan von: Mon Chéri?", a: "Wer kann dazu schon nein sagen" },
    { q: "Wie lautet der Slogan von: Merci?", a: "Dass es dich gibt" },
    { q: "Wie lautet der Slogan von: Toffifee?", a: "Es steckt viel Spaß in Toffifee" },
    { q: "Wie lautet der Slogan von: Hornbach?", a: "Es gibt immer was zu tun" },
    { q: "Wie lautet der Slogan von: Persil?", a: "Da weiß man, was man hat" },
    { q: "Wie lautet der Slogan von: Seitenbacher?", a: "Lecker, lecker, lecker" },
    { q: "Wie lautet der Slogan von: Hipp?", a: "Dafür stehe ich mit meinem Namen" },
    { q: "Wie lautet der Slogan von: Iglo?", a: "Iss was Gscheits" },
    { q: "Wie lautet der Slogan von: Sparkasse?", a: "Wenn's um Geld geht" },
    { q: "Wie lautet der Slogan von: Volksbanken Raiffeisenbanken?", a: "Wir machen den Weg frei" },
    { q: "Wie lautet der Slogan von: Visa?", a: "Die Freiheit nehm ich mir" },
    { q: "Wie lautet der Slogan von: ElitePartner?", a: "Akademiker und Singles mit Niveau" },
    { q: "Wie lautet der Slogan von: Rügenwalder Mühle?", a: "Deftig, kräftig, würzig, gut" },
    { q: "Wie lautet der Slogan von: Ergo?", a: "Versichern heißt verstehen" },
    { q: "Wie lautet der Slogan von: Toyota?", a: "Nichts ist unmöglich" },
    { q: "Wie lautet der Slogan von: Haribo?", a: "Macht Kinder froh und Erwachsene ebenso" },
    { q: "Wie lautet der Slogan von: Red Bull?", a: "Verleiht Flügel" },
    { q: "Wie lautet der Slogan von: Media Markt?", a: "Ich bin doch nicht blöd" },
    { q: "Wie lautet der Slogan von: IKEA?", a: "Wohnst du noch oder lebst du schon" },
    { q: "Wie lautet der Slogan von: Ritter Sport?", a: "Quadratisch Praktisch Gut" },
    { q: "Wie lautet der Slogan von: BMW?", a: "Freude am Fahren" },
    { q: "Wie lautet der Slogan von: Audi?", a: "Vorsprung durch Technik" },
    { q: "Wie lautet der Slogan von: Edeka?", a: "Wir lieben Lebensmittel" },
    { q: "Wie lautet der Slogan von: Carglass?", a: "Repariert, tauscht aus" },
    { q: "Wie lautet der Slogan von: Katjes?", a: "Jes Jes Jes" },
    { q: "Wie lautet der Slogan von: Mastercard?", a: "Unbezahlbar" },
    { q: "Wie lautet der Slogan von: Saturn?", a: "Geiz ist geil" },
    { q: "Wie lautet der Slogan von: Calgon?", a: "Waschmaschinen leben länger mit Calgon" },
    { q: "Wie lautet der Slogan von: Dr. Oetker?", a: "Qualität ist das beste Rezept" },
    { q: "Wie lautet der Slogan von: Knoppers?", a: "Morgens halb 10 in Deutschland" },
    { q: "Wie lautet der Slogan von: Müller Milchreis?", a: "Wenn der kleine Hunger kommt" },
    { q: "Wie lautet der Slogan von: Fisherman's Friend?", a: "Sind sie zu stark, bist du zu schwach" },
    { q: "Wie lautet der Slogan von: Miele?", a: "Immer besser" },
    { q: "Wie lautet der Slogan von: Snickers?", a: "Du bist nicht du, wenn du hungrig bist" },
    { q: "Wie lautet der Slogan von: Apollo Optik?", a: "Da wackelt nix" },
    { q: "Wie lautet der Slogan von: Check24?", a: "Hier check ich alles" },
    { q: "Wie lautet der Slogan von: Deutsche Bahn?", a: "Diese Zeit gehört Dir" },
    { q: "Wie lautet der Slogan von: Rewe?", a: "Dein Markt" },
    { q: "Wie lautet der Slogan von: Lidl?", a: "Lohnt sich" },
    { q: "Wie lautet der Slogan von: Douglas?", a: "Come in and find out" },
    { q: "Wie lautet der Slogan von: Nutella?", a: "Der Morgen macht den Tag" }
  ],
  jobs: [
    { q: "Was ist ein 'Zeidler'?", a: "Ein mittelalterlicher Wald-Imker, der Honig von wilden Bienen sammelte" },
    { q: "Was macht ein 'Oshiya'?", a: "Er drückt in Japan Fahrgäste professionell in überfüllte U-Bahnen" },
    { q: "Was ist ein 'Pechsieder'?", a: "Ein historischer Handwerker, der aus Nadelholz Teer und Pech herstellte" },
    { q: "Was versteht man unter einem 'Abtrittanbieter'?", a: "Jemand, der Passanten gegen Geld einen mobilen Eimer als Toilette anbot" },
    { q: "Was ist ein 'Bierschrotter'?", a: "Ein Arbeiter, der schwere Bierfässer in tiefe Brauereikeller transportierte" },
    { q: "Was ist die Aufgabe eines 'Hühner-Sexers'?", a: "Er bestimmt das Geschlecht von frisch geschlüpften Küken in Sekundenschnelle" },
    { q: "Was bezeichnet man als 'Säckler'?", a: "Ein spezialisierter Lederhandwerker, der Lederhosen und Beutel fertigt" },
    { q: "Was war ein 'Kiepenträger'?", a: "Ein Lastenträger, der Waren in großen Rückenkörben über Gebirgspfade transportierte" },
    { q: "Was ist ein 'Ameisler'?", a: "Jemand, der Ameisenpuppen im Wald sammelte, um sie als Tierfutter zu verkaufen" },
    { q: "Was macht ein 'Putzmacher'?", a: "Ein spezialisierter Handwerker, der Damenhüte entwirft und anfertigt" },
    { q: "Was ist ein 'Groschengräber'?", a: "Ein Arbeiter, der per Hand Brunnen reinigte oder Abwasserkanäle von Schlamm befreite" },
    { q: "Was macht ein 'Mollenhauer'?", a: "Er fertigt aus Holzstämmen Mulden, Backtröge und Waschwannen an" },
    { q: "Was ist ein 'Posamentierer'?", a: "Ein Hersteller von Zierbesätzen wie Kordeln, Quasten und Fransen für Kleidung" },
    { q: "Was versteht man unter einem 'Riemer'?", a: "Ein Lederhandwerker, der Riemen für Pferdegeschirre und Sättel herstellte" },
    { q: "Was ist ein 'Blaudrucker'?", a: "Ein Spezialist für die Stoffveredelung mit einem Reserveverfahren und Indigoblau" },
    { q: "Was macht ein 'Katzenschläger'?", a: "Ein Arbeiter in der alten Textilindustrie, der Wolle mit einem Bogen auflockerte" },
    { q: "Was war die Aufgabe eines 'Vogelstellers'?", a: "Ein professioneller Vogelfänger, der Singvögel für den Verkauf fing" },
    { q: "Was macht ein 'Lector' in einer kubanischen Zigarrenfabrik?", a: "Er liest den Arbeitern während der Produktion Zeitungen oder Romane vor" },
    { q: "Was ist die Aufgabe eines 'Baqueano' in Argentinien?", a: "Ein Fährtensucher, der den Weg durch Wildnis allein an Naturzeichen findet" },
    { q: "Was ist eine 'Ama' in Japan?", a: "Eine traditionelle Taucherin, die ohne Atemgerät nach Perlen und Muscheln sucht" },
    { q: "Was macht ein 'Dabbawala' in Indien?", a: "Er transportiert in einem komplexen System Brotdosen von Wohnungen in Büros" },
    { q: "Was ist ein 'Seringueiro' in Brasilien?", a: "Ein Sammler, der im Regenwald die Gummibäume für Latex anzapft" },
    { q: "Was macht ein 'Fumista' in Italien?", a: "Ein Handwerker für den Bau und Rauchabzug von Kachelöfen" },
    { q: "Was ist ein 'Gomero' in Lateinamerika?", a: "Ein Mechaniker, der ausschließlich Reifenpannen flickt" },
    { q: "Was war ein 'Munshi' in Indien?", a: "Ein Sprachlehrer oder Sekretär für Ausländer" },
    { q: "Was macht ein 'Zanjero' im Südwesten der USA?", a: "Ein Wasseraufseher, der manuell Bewässerungsschleusen regelt" },
    { q: "Was macht ein 'Bodger' in England?", a: "Ein wandernder Drechsler, der direkt im Wald Stuhlbeine fertigt" },
    { q: "Was ist ein 'Aboyeur'?", a: "Ein Küchenmitarbeiter, der die Bestellungen an die Köche ausruft" },
    { q: "Was macht ein 'Dondurmacı'?", a: "Ein türkischer Eisverkäufer, der Kunden mit akrobatischen Tricks neckt" },
    { q: "Was ist ein 'Chicha-Brauer' in Peru?", a: "Er kaut Mais und spuckt ihn zur Fermentierung in einen Topf" },
    { q: "Was ist ein 'Eiszapfen-Hacker' in Russland?", a: "Er schlägt gefährliche Eiszapfen von hohen Dächern" },
    { q: "Was macht ein 'Fahrrad-Fischer' in den Niederlanden?", a: "Er angelt mit Kränen alte Fahrräder aus den Grachten" },
    { q: "Was ist ein 'Gras-Maler' in den USA?", a: "Er besprüht braune Rasenflächen mit grüner Farbe" },
    { q: "Was macht ein 'Miet-Trauergast'?", a: "Er wird bezahlt, um bei Beerdigungen lautstark zu weinen" },
    { q: "Was ist ein 'Schlangen-Melker'?", a: "Er entnimmt per Hand das Gift von lebenden Giftschlangen" },
    { q: "Was macht ein 'Fledermaus-Guano-Sammler'?", a: "Er sammelt in Höhlen Fledermauskot als wertvollen Dünger" },
    { q: "Was ist ein 'Topeiro' in Portugal?", a: "Ein professioneller Maulwurfsfänger auf Golfplätzen" },
    { q: "Was macht ein 'Wellen-Warn-Posten' in Portugal?", a: "Er beobachtet die Brandung und warnt Fischer vor Riesenwellen" },
    { q: "Was ist ein 'Straßen-Trommler' in Tansania?", a: "Er verbreitet Nachrichten trommelnd im ganzen Viertel" },
    { q: "Was macht ein 'Supa-Supa' in Japan?", a: "Er kühlt in Gängen wartende Leute mit riesigen Fächern" },
    { q: "Was ist ein 'Knocker-up'?", a: "Ein historischer Weckdienst, der mit Stöcken an Fenster klopfte" },
    { q: "Was macht ein 'Putter' im Bergbau?", a: "Er schiebt schwere Kohlewagen durch engste Minengänge" }
  ]
};
